K22CNT4_HVK_Project2/Areas/Admin/Controllers/CayController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using K22CNT4_HVK_TTCD1.Models;

namespace K22CNT4_HVK_TTCD1.Areas.Admin.Controllers
{
    /// <summary>
    ///  ĐƯợc tạo ra bới ASP.NET render controller Using entityFramework
    /// </summary>
    public class CayController : Controller
    {
        // lấy mô tả đối tượng database
        private Entities db = new Entities();

        // GET: Admin/Cay
        public ActionResult Index()
        {
            // Gán user bằng session
            var user = Session["User"] as K22CNT4_HVK_TTCD1.Models.NguoiDung;
            // kiểm tra user nếu đúng thì hiển thị danh sách cây
            if (user != null && user.Vaitro == true)
            {
                var cays = db.Cays.Include(c => c.DanhMucCay);
                return View(cays.ToList());
            }else
            {
                // sai, trả về trang đăng nhập
                return RedirectToAction("DangNhap","Home", new { area = "" });
            }
        }

        // GET: Admin/Cay/Details/5
        // Trả về một id lấy từ get form cây có  vidu: id = 5
        public ActionResult Details(int? id)
        {
           // nếu k tìm thấy báo lỗi ra trình duyệt
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // tạo một đôi tượng cây tìm kiếm được theo id tồn tại trong db
            Cay cay = db.Cays.Find(id);
            // Nếu cay rỗng chạy if và trả về lỗi
            if (cay == null)
            {
                return HttpNotFound();
            }
            // Trả về cay nếu các cậu lệnh điều kiện không thỏa mãn
            return View(cay);
        }

        // GET: Admin/Cay/Create
        public ActionResult Create()
        {
            // Hiển thị teend dannh mục tra xuống viewu bag dưới dạng SelectList
            ViewBag.Iddanhmuc = new SelectList(db.DanhMucCays, "Id", "Tendanhmuc");
            return View();
        }

        // POST: Admin/Cay/Create
        // SỬ dụng phuonmgw thức post
        [HttpPost]
        // Sử dụng kiểm tra giá trị
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Tencay,Iddanhmuc,Soluong,Dongia,Hinhanh,Trangthai")] Cay cay)
        {
            // Nếu kiểm tra đúng tra về ModelState đúng và cho phép thêm cây mới
            if (ModelState.IsValid)
            {
                // Thêm cây vào db
                db.Cays.Add(cay);
                // Lưu thay đổi
                db.SaveChanges();
                // Trả về trang hiển thị
                return RedirectToAction("Index");
            }
            // Nếu điều kiện trên k thỏa mãn trả về lại viewBag 1 lần nữa
            ViewBag.Iddanhmuc = new SelectList(db.DanhMucCays, "Id", "Tendanhmuc", cay.Iddanhmuc);
            // Trả về giá trị vừa được nhập vào form trong trường hợp lỗi 
            return View(cay);
        }

        // GET: Admin/Cay/Edit/5
        // Trả về một id lấy từ get form cây có  vidu: id = 5
        public ActionResult Edit(int? id)
        {
            // kiểm tra id nếu null trả về BadRequest 505
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // tạo một đôi tượng cây tìm kiếm được theo id tồn tại trong db
            Cay cay = db.Cays.Find(id);
            // Nếu cay rỗng chạy if và trả về notfound
            if (cay == null)
            {
                return HttpNotFound();
            }
            // Nếu điều kiện trên k thỏa mãn trả về lại viewBag 1 lần nữa
            ViewBag.Iddanhmuc = new SelectList(db.DanhMucCays, "Id", "Tendanhmuc", cay.Iddanhmuc);
            // Trả về giá trị vừa được nhập vào form trong trường hợp lỗi 
            return View(cay);
        }

        // POST: Admin/Cay/Edit/5

        // SỬ dụng phuonmgw thức post
        [HttpPost]
        // Sử dụng kiểm tra giá trị
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Tencay,Iddanhmuc,Soluong,Dongia,Hinhanh,Trangthai")] Cay cay)
        {
            // Nếu kiểm tra đúng tra về ModelState đúng và cho sửa thêm cây mới
            if (ModelState.IsValid)
            {
                db.Entry(cay).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            // Nếu điều kiện trên k thỏa mãn trả về lại viewBag 1 lần nữa
            ViewBag.Iddanhmuc = new SelectList(db.DanhMucCays, "Id", "Tendanhmuc", cay.Iddanhmuc);
            // Trả về giá trị vừa được nhập vào form trong trường hợp lỗi 
            return View(cay);
        }

        // GET: Admin/Cay/Delete/5
        // Lấy id từ get
        public ActionResult Delete(int? id)
        {
            // kiểm tra nếu id rỗng trả về BadRequest
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            // tạo một đối tượng cây lấy từ database
            Cay cay = db.Cays.Find(id);
            // Kiểm tra nếu cay rỗng trả về HttpNotFound
            if (cay == null)
            {
                return HttpNotFound();
            }
            // Nếu k tra về giá trị trước đó
            return View(cay);
        }

        // POST: Admin/Cay/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cay cay = db.Cays.Find(id);
            db.Cays.Remove(cay);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

K22CNT4_HVK_Project2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Web Bán Cây</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/public/css/header.css" />
    <link rel="stylesheet" href="~/public/css/main.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" />
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
</head>
<body>
    @{
        var user = Session["User"] as K22CNT4_HVK_TTCD1.Models.NguoiDung;

    }
    <header class="navbar navbar-light bg-white navbar-expand-sm navbar-toggle able-sm">
        <div class="container">

            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-lg-start ">
                <ul class="navbar-nav flex-grow-1 d-flex justify-content-lg-start fh4">
                    <li>@Html.ActionLink("Trang chủ", "Index", "Home", new { area = "" }, new { @class = "nav-link px-3" })</li>
                    <li>@Html.ActionLink("Tin Tức", "TinTuc", "Home", new { area = "" }, new { @class = "nav-link px-3" })</li>
                    <li class="dropdown">
                        @Html.ActionLink("Cây cảnh", "Cay", "Home", new { area = "" }, new { @class = "nav-link px-3" })
                    </li>
                    <li>@Html.ActionLink("Liên hệ", "LienHe", "Home", new { area = "" }, new { @class = "nav-link px-3" })</li>
                </ul>
            </div>
            <nav class="navbar navbar-light d-flex align-items-center">
                <div class="row">

                    <div class="container">
                        <div class="d-flex justify-content-center align-items-center text-center" style="height: 40px">
                            @{

                                if (user == null)
                                {
                                    <a class="dropdown-item mx-3" href="@Url.Action("DangNhap", "Home", new { area = "" })">Đăng nhập</a>
                                    <a class="dropdown-item" href="@Url.Action("DangKy", "Home", new { area = "" })">Đăng ký</a>
                                }
                                else
                                {
                                    <div class="text-center">
                                        <a class="dropdown-item mx-3 cart-tree text-center d-inline" href="/Cart">
                                            <i class="fa-solid fa-tree"></i>
                                            @if (Session["CartItemCount"] != null && (int)Session["CartItemCount"] > 0)
                                            {
                                                <span class="cart-count">@Session["CartItemCount"]</span>
                                            }
                                            else
                                            {
                                                <span class="cart-count">0</span>
                                            }
                                        </a>
                                    </div>
                                    <a class="dropdown-item mx-3" href="@Url.Action("", "", new { area = "" })">Xin chào @user.Ten</a>
                                    <a class="dropdown-item" href="@Url.Action("DangXuat", "Home", new { area = "" })">Đăng xuất</a>
                                }

                            }


                        </div>
                    </div>
                </div>

            </nav>
        </div>
    </header>
    <!-- end header -->

    <div class="container body-content">
        @RenderBody()

        <hr />
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="tit-footer font22 UTMHelvetIns cl_xanh6 py-4">Web cây cảnh</div>
                    <ul class="nav flex-column">
                        <li class="pb-4 nav-item">
                            <i class="font22 fa fa-home"></i>  <span class="text_foot_color">Văn phòng: Số 5, phố Láng , khu Láng Hạ </span>
                        </li>
                        <li class="pb-4 nav-item">
                            <i class="font22 fa fa-user"></i>  <span class="text_foot_color">Người đại diện: Hoàng Văn Khải </span>
                        </li>
                        <li class="pb-4 nav-item">
                            <i class="font22 fa fa-globe"></i>  <span class="text_foot_color">Mã số thuế: 0424626266622  </span>
                        </li>
                        <li class="pb-4 nav-item">
                            <i class="font22 fa fa-barcode"></i>  <span class="text_foot_color">Hoangvankhai1513@gmail.com</span>
                        </li>
                        <li class="pb-4 nav-item">
                            <i class="font22 fa fa-mobile"></i>  <span class="text_foot_color">Điện thoại: 0123456789 </span>
                        </li>
                    </ul>
                </div>
                <div class="col-sm">
                    <div class="tit-footer font22 UTMHelvetIns cl_xanh6 py-4">Địa chỉ bán buôn bán lẻ</div>
                    <ul class="nav flex-column">
                        <li class="pb-4 nav-item">
                            <span class="text_foot_color mb-3 full bold">Tại Cơ Sở 1</span>
                            <span class="text_foot_color  full">
                                Số 6 - Ngõ 20 <br>
                                láng - Quận Đống Đa - Hà Nội
                            </span>
                            <span class="text_foot_color  full">ĐT:0123456789 </span>
                        </li>
                    </ul>
                </div>
                <div class="col-sm">
                    <div class="tit-footer font22 UTMHelvetIns cl_xanh6 py-4">Danh mục</div>
                    <ul id="nav-footer" class="nav-footer nav-footer list-inline font14">
                        <li id="menu-item-6432" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-6432"><a href="" aria-current="page">Trang Chủ</a></li>
                        <li id="menu-item-15621" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15621"><a href="">Chính sách bảo hành</a></li>
                        <li id="menu-item-15623" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15623"><a href="">Chính sách đổi trả hàng</a></li>
                        <li id="menu-item-15622" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-15622"><a href="">Chính sách bảo mật thông tin</a></li>
                        <li id="menu-item-6439" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-6439"><a href="">Sitemaps</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script>
        var swiperProduct = new Swiper(".mySw", {
            slidesPerView: 5,
            spaceBetween: 30,
            loop: true,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev"
            },
        });
        var swiperProduct = new Swiper(".mySwCay", {
            slidesPerView: 4,
            loop: true,
            grid: {
                rows: 3,
            },
            spaceBetween: 20,
            pagination: {
                el: ".swiper-pagination",
                clickable: true,
            },
        });
        var swiperSlide = new Swiper(".mySwiper", {
            spaceBetween: 30,
            centeredSlides: true,
            loop: true,
            autoplay: {
                delay: 2500,
                disableOnInteraction: false
            },
            pagination: {
                el: ".swiper-pagination",
                clickable: true
            },
            navigation: {
                nextEl: ".swiper-button-next",
                prevEl: ".swiper-button-prev"
            },
            on: {
                autoplayTimeLeft(s, time, progress) {
                    progressCircle.style.setProperty("--progress", 1 - progress);
                    progressContent.textContent = `${Math.ceil(time / 1000)}s`;
                }
            }
        });

    </script>
</body>
</html>